<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="query" nsURI="https://www.example.org/query" nsPrefix="query">
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" lowerBound="1"
        eType="ecore:EClass ../../muslan.musiccollection/model/MusicCollection.ecore#//MusicCollection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" lowerBound="1"
        eType="#//FilterClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//CategorizedElementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterClause" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndClause" eSuperTypes="#//FilterClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterclause" lowerBound="2"
        upperBound="-1" eType="#//FilterClause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrClause" eSuperTypes="#//FilterClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterclause" lowerBound="2"
        upperBound="-1" eType="#//FilterClause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause" abstract="true" eSuperTypes="#//FilterClause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//OperatorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CategorizedElementType">
    <eLiterals name="Track"/>
    <eLiterals name="Album" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorType">
    <eLiterals name="SameAs"/>
    <eLiterals name="DifferentFrom" value="1"/>
    <eLiterals name="LessThan" value="2"/>
    <eLiterals name="GreaterThan" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryClause" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" lowerBound="1"
        eType="ecore:EEnum ../../muslan.musiccollection/model/MusicCollection.ecore#//CategoryType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtistClause" eSuperTypes="#//Clause"/>
  <eClassifiers xsi:type="ecore:EClass" name="TitleClause" eSuperTypes="#//Clause"/>
</ecore:EPackage>
