<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pbconfig" nsURI="https://www.example.org/pbconfig" nsPrefix="pbconfig">
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" upperBound="-1"
        eType="#//ConfigItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigItem" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlagConfig" eSuperTypes="#//ConfigItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Kind" eType="#//BooleanConfig"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberConfig" eSuperTypes="#//ConfigItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Kind" eType="#//IntegerConfig"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanConfig">
    <eLiterals name="Shuffle"/>
    <eLiterals name="SkipUnavailable" value="1" literal="SkipUnavailable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntegerConfig">
    <eLiterals name="SleepTimer"/>
  </eClassifiers>
</ecore:EPackage>
