/*
 * generated by Xtext 2.38.0
 */
package muslan.query.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMuslanQueryScopeProvider extends DelegatingScopeProvider {
}
