/*
 * generated by Xtext 2.38.0
 */
package muslan.query.scoping;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import collection.Collection;
import collection.CollectionRoot;
import query.Query;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */

public class MuslanQueryScopeProvider extends AbstractMuslanQueryScopeProvider {
	
	@Override
	public IScope getScope(EObject context, EReference reference) {
		if(context instanceof Query) {
			Query q = (Query) context;
			EObject root = EcoreUtil.getRootContainer(q);
			if(root instanceof CollectionRoot) {
				CollectionRoot colRoot = (CollectionRoot) root;
				return Scopes.scopeFor(colRoot.getCollection());
			}
		}
		return super.getScope(context, reference);
	}
}
