/*
 * generated by Xtext 2.38.0
 */
package muslan.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MuslanQueryUiModule extends AbstractMuslanQueryUiModule {

	public MuslanQueryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
