/*
 * generated by Xtext 2.38.0
 */
package muslan.query.parser.antlr;

import com.google.inject.Inject;
import muslan.query.parser.antlr.internal.InternalMuslanQueryParser;
import muslan.query.services.MuslanQueryGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MuslanQueryParser extends AbstractAntlrParser {

	@Inject
	private MuslanQueryGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMuslanQueryParser createParser(XtextTokenStream stream) {
		return new InternalMuslanQueryParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Query";
	}

	public MuslanQueryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MuslanQueryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
