/*
 * generated by Xtext 2.38.0
 */
package muslan.query.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MuslanQueryAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("muslan/query/parser/antlr/internal/InternalMuslanQueryParser.tokens");
	}
}
