/*
 * generated by Xtext 2.38.0
 */
package muslan.query.ide;


/**
 * Use this class to register ide components.
 */
public class MuslanQueryIdeModule extends AbstractMuslanQueryIdeModule {
}
