/*
 * generated by Xtext 2.38.0
 */
package muslan.query.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import muslan.query.MuslanQueryRuntimeModule;
import muslan.query.MuslanQueryStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MuslanQueryIdeSetup extends MuslanQueryStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MuslanQueryRuntimeModule(), new MuslanQueryIdeModule()));
	}
	
}
