/*
 * generated by Xtext 2.38.0
 */
package muslan.query;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MuslanQueryStandaloneSetup extends MuslanQueryStandaloneSetupGenerated {

	public static void doSetup() {
		new MuslanQueryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
