<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="collection" nsURI="https://www.example.org/collection" nsPrefix="collection">
  <eClassifiers xsi:type="ecore:EClass" name="Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizedelements" upperBound="-1"
        eType="#//CategorizedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Track" eSuperTypes="#//CategorizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositions" upperBound="-1"
        eType="#//Composition" eOpposite="#//Composition/tracks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album" eSuperTypes="#//CategorizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" lowerBound="1"
        upperBound="-1" eType="#//Track"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//CategorizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" upperBound="-1"
        eType="#//Track" eOpposite="#//Track/compositions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artist">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategorizedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artists" upperBound="-1"
        eType="#//Artist"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" upperBound="-1"
        eType="#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CategoryType" lowerBound="1"
        eType="#//CategoryType" defaultValueLiteral="Genre"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CategoryType">
    <eLiterals name="Rating"/>
    <eLiterals name="Genre" value="1"/>
    <eLiterals name="Tag" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" upperBound="-1"
        eType="#//Collection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artist" upperBound="-1"
        eType="#//Artist" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../muslan.pbconfig/model/pbconfig.ecore#//Configuration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultConfig" lowerBound="1"
        eType="ecore:EClass ../../muslan.pbconfig/model/pbconfig.ecore#//Configuration"/>
  </eClassifiers>
</ecore:EPackage>
