<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="musiccollection" nsURI="https://www.example.org/musiccollection" nsPrefix="musiccollection">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MusicCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizedelements" upperBound="-1"
        eType="#//CategorizedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Track" eSuperTypes="#//CategorizedElement ../../muslan.playlist/model/playlist.ecore#//PlayItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositions" upperBound="-1"
        eType="#//Composition" eOpposite="#//Composition/tracks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album" eSuperTypes="#//CategorizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" lowerBound="1"
        upperBound="-1" eType="#//Track"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//CategorizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" upperBound="-1"
        eType="#//Track" eOpposite="#//Track/compositions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artist">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategorizedElement" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NameIsLowerCase"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NameIsLowerCase" value="Tuple {&#xA;&#x9;message : String = 'Expected a lowercase name rather than '' + Name + ''',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;Name = Name?.toLowerCase()&#xA;}.status"/>
    </eAnnotations>
    <eOperations name="ucName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="Name?.toUpperCase()"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artists" upperBound="-1"
        eType="#//Artist"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" upperBound="-1"
        eType="#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CategoryType" lowerBound="1"
        eType="#//CategoryType" defaultValueLiteral="Genre"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CategoryType">
    <eLiterals name="Rating"/>
    <eLiterals name="Genre" value="1"/>
    <eLiterals name="Tag" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="musiccollection" upperBound="-1"
        eType="#//MusicCollection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artist" upperBound="-1"
        eType="#//Artist" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../muslan.pbconfig/model/pbconfig.ecore#//Configuration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultConfig" lowerBound="1"
        eType="ecore:EClass ../../muslan.pbconfig/model/pbconfig.ecore#//Configuration"/>
  </eClassifiers>
</ecore:EPackage>
